version:
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/checkout
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit
